### ISSUE TITLE
aggiungere open graph

### ISSUE THREAD

**Issue by aborruso** [ondata/italian-public-sector-pnrr-data-guide#3]

**Comment by dennisangemi** [comment]
Ne ho fatta una rapidissima con dimensioni 1200×630

qui 1x
![og-italian-public-sector-pnrr-data-guide](https://user-images.githubusercontent.com/77018886/218839335-3b1ef05c-e317-4c6b-ba2f-ad50f9a2fd42.png)
qui 2x
<img width="1200" alt="og-italian-public-sector-pnrr-data-guide-2x" src="https://user-images.githubusercontent.com/77018886/218839367-4af7cfe4-ea50-4076-83fd-be96e582a989.png">

baci

**Comment by aborruso** [comment]
Caro @dennisangemi  per il momento ne ho usato un'altra.

Grazie mille
