### ISSUE TITLE
coerenza ordine risorse

### ISSUE THREAD

**Issue by dennisangemi** [ondata/italian-public-sector-pnrr-data-guide#5]
Ciao @aborruso, nel suggerimento relativo alle fonti dati nazionali (nell'introduzione) si legge
https://github.com/ondata/italian-public-sector-pnrr-data-guide/blob/3244de7cdd6f8c5233d45eb183886277921e1749/introduzione.qmd#L31

ma la prima risorsa è 
https://github.com/ondata/italian-public-sector-pnrr-data-guide/blob/3244de7cdd6f8c5233d45eb183886277921e1749/introduzione.qmd#L23

**Comment by aborruso** [comment]
> ma la prima risorsa è

E partendo da lì, si legge

> ancora poco relativamente a livello di progetti e stato di avanzamento

Quindi si legge in ordine e la prima si scarta per questo. Ma hai ragione.
Ci ragiono un po' su

Grazie
